<?php

class MobWeb_NewsletterSignupCoupon_Helper_Data extends Mage_Core_Helper_Abstract
{
    public $log_file = 'mobweb_newslettersignupcoupon.log';

    public function createCoupons($count = 1, $string = '')
    {
        // Get the shopping cart price rule from the ID specified
        // in the configuration
        $shopping_cart_price_rule_id = Mage::getStoreConfig('newsletter/newslettersignupcoupon/shopping_cart_price_rule_id');
        $rule = Mage::getModel('salesrule/rule')->load($shopping_cart_price_rule_id);

        // Check if an existing rule was retreived, if not, abort
        if($rule->isObjectNew()) {
            // Create a log entry
            Mage::helper('newslettersignupcoupon')->log('Invalid or unknown shopping cart price rule ID specified: ' . $shopping_cart_price_rule_id);
            return false;
        }
        
        // Define a coupon code generator model instance
        // Look at Mage_SalesRule_Model_Coupon_Massgenerator for options
        $generator = Mage::getModel('salesrule/coupon_massgenerator');

        $parameters = array(
            'count' => $count,
            'format' => 'alphanumeric',
            'dash_every_x_characters' => 4,
            'prefix' => $string . '-',
            'suffix' => '',
            'length' => 4
        );

        if(!empty($parameters['format'])){
          switch(strtolower($parameters['format'])){
            case 'alphanumeric':
            case 'alphanum':
              $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHANUMERIC);
              break;
            case 'alphabetical':
            case 'alpha':
              $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_ALPHABETICAL);
              break;
            case 'numeric':
            case 'num':
              $generator->setFormat(Mage_SalesRule_Helper_Coupon::COUPON_FORMAT_NUMERIC);
              break;
          }
        }

        $generator->setDash(!empty($parameters['dash_every_x_characters'])? (int) $parameters['dash_every_x_characters'] : 0);
        $generator->setLength(!empty($parameters['length']) ? (int) $parameters['length'] : 6);
        $generator->setPrefix(!empty($parameters['prefix']) ? $parameters['prefix'] : '');
        $generator->setSuffix(!empty($parameters['suffix']) ? $parameters['suffix'] : '');

        // Set the generator, and coupon type so it's able to generate
        $rule->setCouponCodeGenerator($generator);
        $rule->setCouponType(Mage_SalesRule_Model_Rule::COUPON_TYPE_AUTO);

        // Get as many coupons as you required
        $count = !empty($parameters['count']) ? (int) $parameters['count'] : 1;
        $codes = array();

        for($i = 0; $i < $count; $i++) {
            $coupon = $rule->acquireCoupon()->setType(Mage_SalesRule_Helper_Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)->save();
            $code = $coupon->getCode();
            $codes[] = $code;
        }

        return $codes;
    }

    public function sendCoupon($email) {

        // Create the coupon code
        $coupon_code = Mage::helper('newslettersignupcoupon')->createCoupons(1, 'newsletter');
        if($coupon_code = $coupon_code[0]) {
            // Load the transactional email specified in the config
            $transactional_email_id = Mage::getStoreConfig('newsletter/newslettersignupcoupon/transactional_email_id');
            $transactional_email = Mage::getModel('core/email_template')->load($transactional_email_id);

            // Check if the transactional email exists
            if($transactional_email->isObjectNew()) {
                // Create a log entry
                Mage::helper('newslettersignupcoupon')->log('Invalid or unknown transactional email ID specified: ' . $transactional_email_id);
                return false;
            }

            // Send the coupon code
            Mage::getModel('core/email_template')->sendTransactional(
                $transactional_email->getId(),
                array(
                    'name' => Mage::getStoreConfig('trans_email/ident_support/name'),
                    'email' =>  Mage::getStoreConfig('trans_email/ident_support/email')
                ),
                $email,
                $email,
                array('coupon_code' => $coupon_code),
                Mage::app()->getStore()->getId()
            );

            // Create a log entry
            Mage::helper('newslettersignupcoupon')->log('Sending coupon code to user: ' . $email);
        }
    }

    public function log($msg)
    {
        Mage::log($msg, NULL, $this->log_file);
    }
}